import { randomUUID } from 'node:crypto'
import type { SelectedCredential } from '../domain/types.js'
import { GatewayError } from '../errors.js'

export const allowedMessageBodyKeys = new Set([
  'model',
  'messages',
  'system',
  'tools',
  'tool_choice',
  'betas',
  'metadata',
  'max_tokens',
  'thinking',
  'temperature',
  'context_management',
  'output_config',
  'speed',
  'stream',
])

const upstreamDroppedBodyKeys = new Set([
  // Claude Code may include this beta-only field, but the Claude.ai OAuth
  // Messages endpoint currently rejects it with "Extra inputs are not permitted".
  'context_management',
])

export type MessageRequest = Record<string, unknown> & {
  model?: unknown
  messages?: unknown
  stream?: unknown
  metadata?: unknown
}

export type AdaptedMessageRequest = {
  body: Record<string, unknown>
  headers: Record<string, string>
  clientRequestId: string
  signal?: AbortSignal
}

type HeaderSource = Headers | Record<string, string>

const blockedForwardedClientHeaders = new Set([
  'anthropic-api-key',
  'anthropic-auth-token',
  'anthropic-organization-id',
])

function headerEntries(input?: HeaderSource): Array<[string, string]> {
  if (!input) return []
  if (input instanceof Headers) return [...input.entries()]
  return Object.entries(input)
}

function extractForwardedClientHeaders(input?: HeaderSource): Record<string, string> {
  const forwarded: Record<string, string> = {}
  for (const [rawName, value] of headerEntries(input)) {
    const name = rawName.toLowerCase()
    if (blockedForwardedClientHeaders.has(name)) {
      continue
    }
    if (name === 'user-agent') {
      forwarded['User-Agent'] = value
      continue
    }
    if (name.startsWith('anthropic-') || name.startsWith('x-stainless-')) {
      forwarded[name] = value
    }
  }
  return forwarded
}

function assertSupportedBody(body: MessageRequest): void {
  for (const key of Object.keys(body)) {
    if (!allowedMessageBodyKeys.has(key)) {
      throw new GatewayError(
        'gateway_validation_error',
        `Unsupported Messages request field: ${key}`,
        400,
      )
    }
  }
  if (typeof body.model !== 'string' || body.model.length === 0) {
    throw new GatewayError('gateway_validation_error', 'model is required', 400)
  }
  if (!Array.isArray(body.messages)) {
    throw new GatewayError(
      'gateway_validation_error',
      'messages must be an array',
      400,
    )
  }
}

function buildGatewayMetadata(
  credential: SelectedCredential,
): Record<string, unknown> {
  const sessionId =
    credential.upstreamSessionId ?? credential.account.upstreamClientIdentityId
  // Claude Code sends metadata.user_id as a JSON string containing device,
  // account, and session identity. We keep it account-scoped and generated by
  // the gateway so downstream clients cannot spoof upstream identity fields.
  return {
    user_id: JSON.stringify({
      device_id: credential.account.upstreamClientIdentityId,
      account_uuid: credential.account.accountUuid,
      session_id: sessionId,
    }),
  }
}

export function adaptMessagesRequest(input: {
  body: MessageRequest
  credential: SelectedCredential
  userAgent: string
  downstreamHeaders?: HeaderSource
  appName?: string
  clientRequestId?: string
  signal?: AbortSignal
}): AdaptedMessageRequest {
  assertSupportedBody(input.body)

  const clientRequestId = input.clientRequestId ?? randomUUID()
  const upstreamSessionId =
    input.credential.upstreamSessionId ??
    input.credential.account.upstreamClientIdentityId
  const body: Record<string, unknown> = { ...input.body }
  for (const key of upstreamDroppedBodyKeys) {
    delete body[key]
  }
  body.metadata = buildGatewayMetadata(input.credential)

  const forwardedHeaders = extractForwardedClientHeaders(input.downstreamHeaders)
  const headers: Record<string, string> = {
    ...forwardedHeaders,
    Authorization: `Bearer ${input.credential.token.accessToken}`,
    'User-Agent': forwardedHeaders['User-Agent'] ?? input.userAgent,
    'x-app': input.appName ?? 'cli',
    'X-Claude-Code-Session-Id': upstreamSessionId,
    'x-client-request-id': clientRequestId,
  }

  return { body, headers, clientRequestId, signal: input.signal }
}
